"""TerraQuest CV pipeline v0.2 - thesis theta/r comparison sweep (lane two).

Compares the two thesis theta candidates (0.1 rad structure-identification,
p. 18; 0.2 rad dynamics, pp. 22-23) against our demo r and a small cell-radius
ladder, on Juan's public Drive frames (pictures_Saturns).

Honesty rules - nothing is silently pinned:
  * thesis r_min = 3 px; our float_range_hk r is a cell-index window over the
    angle matrix whose spacing is FlowParams.res px. The px->cell mapping is
    NOT stated in the thesis (THESIS_PARAMS.md section 3), so the sweep
    reports both readings per run and pins nothing.
  * score.py stays a stub: no u16 is produced here; score_formula = PENDING.
  * demo r=0 is reported as-is alongside the ladder, never replaced.

Output: realrun/THETA_SWEEP.md (table + JSON), one JSON line per run on
stdout for the job log.
"""
from __future__ import annotations

import itertools
import json
import os

import numpy as np

from pipeline.clusters import big_work2
from pipeline.config import ClusterParams, FlowParams
from realrun import N_SAT, SATURNS_ID, fetch_frames

THETAS = (0.1, 0.2)
RS = (0, 1, 2, 3)
N_CLUSTERS = 20


def main() -> None:
    base = os.path.join(os.path.dirname(os.path.abspath(__file__)), "realrun")
    sat = fetch_frames(SATURNS_ID, os.path.join(base, "pictures_Saturns"), N_SAT)
    if len(sat) < 3:
        raise SystemExit(f"need >=3 Saturns frames, got {len(sat)}")
    folder = os.path.dirname(sat[0])
    fp = FlowParams()

    report = {
        "pipeline_version": "cv-pipeline v0.2",
        "purpose": "thesis theta comparison (0.1 structure / 0.2 dynamics) x aligned cell radii",
        "score_formula": "PENDING (score.py stub; no u16 produced)",
        "r_pin": "PENDING - sweep reports, never substitutes",
        "unit_mapping": (
            f"thesis r is px; ours is a cell window; grid spacing = {fp.res} px/cell. "
            "thesis 3 px < one cell at this res -> literal sub-cell reading = r_cells 0; "
            f"r_cells 1..{RS[-1]} = {fp.res}..{RS[-1] * fp.res} px windows. "
            "thesis own LK res 10 px (3 px still sub-cell there); conversion not stated."
        ),
        "source": "Juan Drive Paenibacillus_tracking (public), fetched in CI",
        "n_clusters": N_CLUSTERS,
        "runs": {},
    }

    for theta, r in itertools.product(THETAS, RS):
        label = "theta%s_r%s" % (theta, r)
        L = big_work2(N_CLUSTERS, folder, 0, ClusterParams(r=r, theta=theta), fp)
        fin = L[~np.isnan(L)]
        uniq, counts = np.unique(fin, return_counts=True)
        order = np.argsort(counts)[::-1]
        rec = {
            "theta": theta,
            "r_cells": r,
            "r_window_px": r * fp.res,
            "labels_found": int(uniq.size),
            "labeled_cells": int(fin.size),
            "largest_cluster_cells": int(counts[order[0]]) if counts.size else 0,
            "top_sizes": [int(counts[i]) for i in order[:8]],
            "grid": [int(x) for x in L.shape],
        }
        report["runs"][label] = rec
        print("run_%s: %s" % (label, json.dumps(rec)))

    md = [
        "# cv-pipeline v0.2 - thesis theta comparison sweep",
        "",
        "Generated by .github/workflows/cv-theta-sweep.yml on Juan's public Drive",
        "frames (pictures_Saturns). theta = thesis candidates (0.1 structure,",
        "0.2 rad dynamics); r = cell-radius ladder with px equivalence reported.",
        "Nothing here pins r or the score - both stay PENDING per cv/README.md.",
        "",
        "| theta | r_cells | r_window_px | labels_found | labeled_cells | largest |",
        "|---|---|---|---|---|---|",
    ]
    for _label, rec in report["runs"].items():
        md.append(
            "| %s | %s | %s | %s | %s | %s |"
            % (
                rec["theta"],
                rec["r_cells"],
                rec["r_window_px"],
                rec["labels_found"],
                rec["labeled_cells"],
                rec["largest_cluster_cells"],
            )
        )
    md += ["", "```json", json.dumps(report, indent=2, default=str), "```", ""]
    out = os.path.join(base, "THETA_SWEEP.md")
    with open(out, "w") as fh:
        fh.write("\n".join(md))
    print("THETA_SWEEP.md written (%s)" % out)


if __name__ == "__main__":
    main()
