[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
terraquest_mint = "CurN8UWQwD1pifo9rhzKLbVrJxNt5jiGDTtpT8h6KskS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
